/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sn.ugb.ipsl.projet_fin_annee.Gui;

import javax.swing.JOptionPane;
import sn.ugb.ipsl.projet_fin_annee.entite.filieres;
import sn.ugb.ipsl.projet_fin_annee.service.filiere_implemente;

/**
 *
 * @author mac
 */
public class creatFilierePanel extends javax.swing.JPanel {

    filiere_implemente filiere = new filiere_implemente();

    /**
     * Creates new form creatFilierePanel
     */
    public creatFilierePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TextFieldNOMFILIERE = new javax.swing.JTextField();
        ButtonAnnuler2 = new javax.swing.JButton();
        ButtonModiffier = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setBorder(javax.swing.BorderFactory.createTitledBorder("BIENVENUE"));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("AJOUTER FILIERE");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DONNER LE NOM DE LA FILIERE");

        TextFieldNOMFILIERE.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextFieldNOMFILIERE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNOMFILIEREActionPerformed(evt);
            }
        });

        ButtonAnnuler2.setText("Annuler");
        ButtonAnnuler2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAnnuler2ActionPerformed(evt);
            }
        });

        ButtonModiffier.setText("Ajouter");
        ButtonModiffier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonModiffierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                            .addComponent(TextFieldNOMFILIERE))
                        .addGap(0, 109, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(ButtonAnnuler2)
                .addGap(18, 18, 18)
                .addComponent(ButtonModiffier)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(TextFieldNOMFILIERE, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonAnnuler2)
                    .addComponent(ButtonModiffier))
                .addGap(189, 189, 189))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldNOMFILIEREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNOMFILIEREActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNOMFILIEREActionPerformed

    private void ButtonAnnuler2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAnnuler2ActionPerformed
        TextFieldNOMFILIERE.setText("");
    }//GEN-LAST:event_ButtonAnnuler2ActionPerformed

    private void ButtonModiffierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonModiffierActionPerformed

        String nom = TextFieldNOMFILIERE.getText();
        if (nom == null || nom.isBlank()) {
            JOptionPane.showMessageDialog(this, "Le nom de la filiere est obligatoire", "ERREUR NOM", JOptionPane.ERROR_MESSAGE);
            return;
        }

        filiere.ajout_filiere(new filieres(nom));

        main_apps app = main_apps.getinstance();
        app.setContentPane(new listerEtudiantPanel());
        app.revalidate();
        app.repaint();
        JOptionPane.showMessageDialog(this, "la filiere est ajouter", "ERREUR NOM", JOptionPane.INFORMATION_MESSAGE);
        TextFieldNOMFILIERE.setText("");
    }//GEN-LAST:event_ButtonModiffierActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAnnuler2;
    private javax.swing.JButton ButtonModiffier;
    private javax.swing.JTextField TextFieldNOMFILIERE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
