/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sn.ugb.ipsl.projet_fin_annee.Gui;

import javax.swing.JOptionPane;
import sn.ugb.ipsl.projet_fin_annee.service.etudiant_implemente;
import sn.ugb.ipsl.projet_fin_annee.entite.Etudiant;
import sn.ugb.ipsl.projet_fin_annee.service.filiere_implemente;

/**
 *
 * @author mac
 */
public class createEtudiantPanel extends javax.swing.JPanel {

    etudiant_implemente etudiantservice = new etudiant_implemente();

    filiere_implemente filiere = new filiere_implemente();
    /**
     * Creates new form createEtudiantPanel
     */
    public createEtudiantPanel() {
        initComponents();
        
        
        String a[]=new String[200];
        a=new String[200];;
        for (int i = 0; i < filiere.lister_filiere().size() ; i++) {
            a[i]=filiere.lister_filiere().get(i).getNomf() ;
        }
        
        ComboBoxFILIERE.setModel(new javax.swing.DefaultComboBoxModel<>(a));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TextFieldID = new javax.swing.JTextField();
        TextFieldNOM = new javax.swing.JTextField();
        TextFieldPRENON = new javax.swing.JTextField();
        TextFieldDATEDENaissance = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ComboBoxFILIERE = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        ComboBoxNIVEAU = new javax.swing.JComboBox<>();
        ButtonENTRE = new javax.swing.JButton();
        ButtonANNULER = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setBackground(new java.awt.Color(0, 153, 153));
        setBorder(javax.swing.BorderFactory.createTitledBorder("BIENVENUE"));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 3, 13)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AJOUTER ETUDIANT");

        jLabel2.setText("ID:");

        jLabel3.setText("PRENON:");

        jLabel4.setText("NOM:");

        jLabel5.setText("DATE DE NAISSANCE:");

        jLabel6.setText("(AAAA-MM-JJ)");

        TextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldIDActionPerformed(evt);
            }
        });

        jLabel7.setText("FILIERE");

        ComboBoxFILIERE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INFORMATIQUE", "GESTION", "MECANIQUE", "GENI CIVIL" }));
        ComboBoxFILIERE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxFILIEREActionPerformed(evt);
            }
        });

        jLabel8.setText("NIVEAU");

        ComboBoxNIVEAU.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Licence1", "Licence2", "Licence3", "Master1", "Master2"}));
        ComboBoxNIVEAU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxNIVEAUActionPerformed(evt);
            }
        });

        ButtonENTRE.setText("Enregisterr");
        ButtonENTRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonENTREActionPerformed(evt);
            }
        });

        ButtonANNULER.setText("Annuler");
        ButtonANNULER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonANNULERActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ComboBoxFILIERE, 0, 96, Short.MAX_VALUE)
                            .addComponent(TextFieldNOM)
                            .addComponent(TextFieldPRENON, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextFieldDATEDENaissance)
                            .addComponent(TextFieldID)
                            .addComponent(ComboBoxNIVEAU, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(1, 1, 1)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(ButtonANNULER)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonENTRE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldNOM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldPRENON, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TextFieldDATEDENaissance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxFILIERE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxNIVEAU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonENTRE)
                    .addComponent(ButtonANNULER))
                .addContainerGap(44, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxFILIEREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxFILIEREActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxFILIEREActionPerformed

    private void ButtonANNULERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonANNULERActionPerformed
        TextFieldID.setText("");
        TextFieldDATEDENaissance.setText("");
        TextFieldNOM.setText("");
        TextFieldPRENON.setText("");
    }//GEN-LAST:event_ButtonANNULERActionPerformed

    private void ComboBoxNIVEAUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxNIVEAUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxNIVEAUActionPerformed

    private void ButtonENTREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonENTREActionPerformed

        String id = TextFieldID.getText();
        String nom = TextFieldNOM.getText();
        String prenom = TextFieldPRENON.getText();
        String datedenaissance = TextFieldDATEDENaissance.getText();
        String filiere = ComboBoxFILIERE.getSelectedItem().toString();
        String niveau = ComboBoxNIVEAU.getSelectedItem().toString();

        if (id == null || id.isBlank() || nom == null || nom.isBlank() || prenom == null || prenom.isBlank()) {
            JOptionPane.showMessageDialog(this, "tout les champs sont oblicatoir!", "formulere invalide", JOptionPane.ERROR_MESSAGE);
            return;
        }
        etudiantservice.ajout_etudiant(new Etudiant(id, prenom, nom, datedenaissance, niveau, filiere));

        JOptionPane.showMessageDialog(this, "l'etudiant a ete enregistrer avec succes", "formulere valide", JOptionPane.INFORMATION_MESSAGE);
        ButtonANNULERActionPerformed(evt);

        main_apps app = main_apps.getinstance();
        app.setContentPane(new listerEtudiantPanel());
        app.revalidate();
        app.repaint();


    }//GEN-LAST:event_ButtonENTREActionPerformed

    private void TextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonANNULER;
    private javax.swing.JButton ButtonENTRE;
    private javax.swing.JComboBox<String> ComboBoxFILIERE;
    private javax.swing.JComboBox<String> ComboBoxNIVEAU;
    private javax.swing.JTextField TextFieldDATEDENaissance;
    private javax.swing.JTextField TextFieldID;
    private javax.swing.JTextField TextFieldNOM;
    private javax.swing.JTextField TextFieldPRENON;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
